### PR TITLE
fix(content items): make locale nullable

### PR DESCRIPTION
**Pull request by rs-amp**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Build (`npm run build`) was run locally and any changes were pushed
- [x] Tests (`npm run test`) for the changes have been added (for bug fixes / features)
- [x] Docs (`npm run doc`) have been reviewed and added / updated if needed (for bug fixes / features)
- [x] PR title and git commit messages conform to the [conventionalcommits](https://www.conventionalcommits.org/en/v1.0.0/) specification

## Pull request type

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behaviour?
Locale is not present on the ContentItem type, but it is regularly undefined when returned by DC.

## What is the new behaviour?
The type definition now allows `locale` to be undefin

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

This may cause typescript compilers to require a null check. I'm not sure if this counts as a breaking change, feel free to comment if it is.

## Other information

Needed for `fix/locale` over in `dc-cli`

### CODE REVIEW

**Review by simonmudd — CHANGES_REQUESTED** [review]
Could we add a test to make sure that nothing breaks with this change if the locale is not supplied?

**Comment by rs-amp** [comment]
> Could we add a test to make sure that nothing breaks with this change if the locale is not supplied?

I'm not sure what I'd be testing here. The one use of the locale field within this project is a test for the `set-locale` endpoint, and the field itself is set via an `Object.assign`. Do you want a test getting content items using fixtures with the field present and not present?

**Review by PikinerLiliya — APPROVED** [review]

**Comment by simonmudd** [comment]
> > Could we add a test to make sure that nothing breaks with this change if the locale is not supplied?
> 
> I'm not sure what I'd be testing here. The one use of the locale field within this project is a test for the `set-locale` endpoint, and the field itself is set via an `Object.assign`. Do you want a test getting content items using fixtures with the field present and not present?

Yes please, tests around the field being present and not would be very helpful. Does the set-locale endpoint handle an undefined value?

**Comment by rs-amp** [comment]
> > > Could we add a test to make sure that nothing breaks with this change if the locale is not supplied?
> > 
> > 
> > I'm not sure what I'd be testing here. The one use of the locale field within this project is a test for the `set-locale` endpoint, and the field itself is set via an `Object.assign`. Do you want a test getting content items using fixtures with the field present and not present?
> 
> Yes please, tests around the field being present and not would be very helpful. Does the set-locale endpoint handle an undefined value?

`setLocale` currently only takes a defined locale, which is fine as the locale cannot be set undefined again after it is created on DC (gives LOCALE_IMMUTABLE error).

I've added a test which should trigger a typescript error if the locale field cannot be undefined, after speaking with marc.

**Review by easen-amp — APPROVED** [review]

**Review by simonmudd — APPROVED** [review]

**Pull request merged**
